language: java
jdk:
  - openjdk8
before_install:
  - chmod +x gradlew
branches:
  only:
    - develop
  except:
    - legacy

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료시 알람
notifications:
    email:
      recipients:
        - 940love@naver.com
    slack: nexters-moss:0ZD2IZ1qHh0S5TAPR8PTnTj5